# Generated by Django 3.0 on 2019-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_media', '0002_auto_20191212_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
